name = Elegant
description = layout for Westbay Hair Extensions
preview = westbay.png
template = elegant-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Stylesheets
; ========================================

stylesheets[all][] = css/layouts/elegant/elegant-layout.css
stylesheets[all][] = css/layouts/elegant/elegant.layout.styles.css
